# Aplicação WEB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtemp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtemp
  template:
    metadata:
      labels:
        app: webtemp
    spec:
      containers:
        - name: webtemp
          image: desenvolvimentovitoria/conversao-temperatura:v1
          ports:
            - containerPort: 8080
---
# Service da aplicação WEB
apiVersion: v1
kind: Service
metadata:
  name: webtemp
spec:
  selector:
    app: webtemp
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  